### ISSUE TITLE
Screenshot of your phone homescreen.

### ISSUE THREAD

**Issue by AchoArnold** [SITZ/ama#1]

**Comment by sitz** [comment]
Thanks for asking!
Although, I keep customizing home screen, this is current one.
![screenshot_20161226-184207](https://cloud.githubusercontent.com/assets/356043/21482536/26f5b566-cb9b-11e6-8d21-c1a56be2b55a.png)

**Comment by AchoArnold** [comment]
Thanks for the answer. Is that a nexus 6p?

**Comment by sitz** [comment]
That's a 2 year old [OnePlus One](https://oneplus.net/one).
